# Generated by Django 5.0.6 on 2024-05-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../https://res-console.cloudinary.com/dx5y0mmme/thumbnails/v1/image/upload/v1715679145/bWVkaWEvaW1hZ2VzL2RlZmF1bHRfcHJvZmlsZV9yZWx4b3M=/drilldown', upload_to='images/'),
        ),
    ]
