# Generated by Django 5.0.6 on 2024-05-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../https://res.cloudinary.com/dx5y0mmme/image/upload/v1715679145/media/images/default_profile_relxos.jpg', upload_to='images/'),
        ),
    ]
